#!/bin/bash 
#SBATCH --ntasks=216
#SBATCH --output=./output.txt
#SBATCH --cpus-per-task=16
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs2_msp2_aTrue_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs2_msp2_aTrue_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs2_msp2_aTrue_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs2_msp2_aFalse_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs2_msp2_aFalse_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs2_msp2_aFalse_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs2_msp10_aTrue_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs2_msp10_aTrue_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs2_msp10_aTrue_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs2_msp10_aFalse_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs2_msp10_aFalse_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs2_msp10_aFalse_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs2_msp50_aTrue_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs2_msp50_aTrue_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs2_msp50_aTrue_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs2_msp50_aFalse_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs2_msp50_aFalse_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs2_msp50_aFalse_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs2_msp100_aTrue_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs2_msp100_aTrue_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs2_msp100_aTrue_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs2_msp100_aFalse_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs2_msp100_aFalse_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs2_msp100_aFalse_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs2_msp200_aTrue_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs2_msp200_aTrue_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs2_msp200_aTrue_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs2_msp200_aFalse_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs2_msp200_aFalse_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs2_msp200_aFalse_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs2_msp500_aTrue_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs2_msp500_aTrue_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs2_msp500_aTrue_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs2_msp500_aFalse_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs2_msp500_aFalse_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs2_msp500_aFalse_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs10_msp2_aTrue_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs10_msp2_aTrue_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs10_msp2_aTrue_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs10_msp2_aFalse_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs10_msp2_aFalse_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs10_msp2_aFalse_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs10_msp10_aTrue_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs10_msp10_aTrue_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs10_msp10_aTrue_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs10_msp10_aFalse_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs10_msp10_aFalse_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs10_msp10_aFalse_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs10_msp50_aTrue_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs10_msp50_aTrue_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs10_msp50_aTrue_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs10_msp50_aFalse_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs10_msp50_aFalse_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs10_msp50_aFalse_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs10_msp100_aTrue_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs10_msp100_aTrue_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs10_msp100_aTrue_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs10_msp100_aFalse_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs10_msp100_aFalse_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs10_msp100_aFalse_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs10_msp200_aTrue_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs10_msp200_aTrue_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs10_msp200_aTrue_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs10_msp200_aFalse_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs10_msp200_aFalse_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs10_msp200_aFalse_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs10_msp500_aTrue_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs10_msp500_aTrue_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs10_msp500_aTrue_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs10_msp500_aFalse_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs10_msp500_aFalse_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs10_msp500_aFalse_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs50_msp2_aTrue_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs50_msp2_aTrue_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs50_msp2_aTrue_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs50_msp2_aFalse_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs50_msp2_aFalse_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs50_msp2_aFalse_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs50_msp10_aTrue_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs50_msp10_aTrue_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs50_msp10_aTrue_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs50_msp10_aFalse_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs50_msp10_aFalse_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs50_msp10_aFalse_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs50_msp50_aTrue_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs50_msp50_aTrue_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs50_msp50_aTrue_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs50_msp50_aFalse_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs50_msp50_aFalse_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs50_msp50_aFalse_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs50_msp100_aTrue_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs50_msp100_aTrue_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs50_msp100_aTrue_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs50_msp100_aFalse_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs50_msp100_aFalse_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs50_msp100_aFalse_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs50_msp200_aTrue_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs50_msp200_aTrue_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs50_msp200_aTrue_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs50_msp200_aFalse_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs50_msp200_aFalse_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs50_msp200_aFalse_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs50_msp500_aTrue_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs50_msp500_aTrue_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs50_msp500_aTrue_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs50_msp500_aFalse_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs50_msp500_aFalse_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs50_msp500_aFalse_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs100_msp2_aTrue_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs100_msp2_aTrue_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs100_msp2_aTrue_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs100_msp2_aFalse_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs100_msp2_aFalse_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs100_msp2_aFalse_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs100_msp10_aTrue_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs100_msp10_aTrue_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs100_msp10_aTrue_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs100_msp10_aFalse_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs100_msp10_aFalse_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs100_msp10_aFalse_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs100_msp50_aTrue_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs100_msp50_aTrue_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs100_msp50_aTrue_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs100_msp50_aFalse_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs100_msp50_aFalse_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs100_msp50_aFalse_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs100_msp100_aTrue_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs100_msp100_aTrue_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs100_msp100_aTrue_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs100_msp100_aFalse_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs100_msp100_aFalse_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs100_msp100_aFalse_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs100_msp200_aTrue_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs100_msp200_aTrue_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs100_msp200_aTrue_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs100_msp200_aFalse_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs100_msp200_aFalse_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs100_msp200_aFalse_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs100_msp500_aTrue_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs100_msp500_aTrue_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs100_msp500_aTrue_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs100_msp500_aFalse_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs100_msp500_aFalse_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs100_msp500_aFalse_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs200_msp2_aTrue_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs200_msp2_aTrue_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs200_msp2_aTrue_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs200_msp2_aFalse_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs200_msp2_aFalse_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs200_msp2_aFalse_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs200_msp10_aTrue_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs200_msp10_aTrue_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs200_msp10_aTrue_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs200_msp10_aFalse_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs200_msp10_aFalse_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs200_msp10_aFalse_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs200_msp50_aTrue_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs200_msp50_aTrue_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs200_msp50_aTrue_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs200_msp50_aFalse_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs200_msp50_aFalse_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs200_msp50_aFalse_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs200_msp100_aTrue_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs200_msp100_aTrue_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs200_msp100_aTrue_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs200_msp100_aFalse_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs200_msp100_aFalse_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs200_msp100_aFalse_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs200_msp200_aTrue_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs200_msp200_aTrue_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs200_msp200_aTrue_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs200_msp200_aFalse_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs200_msp200_aFalse_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs200_msp200_aFalse_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs200_msp500_aTrue_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs200_msp500_aTrue_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs200_msp500_aTrue_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs200_msp500_aFalse_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs200_msp500_aFalse_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs200_msp500_aFalse_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs500_msp2_aTrue_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs500_msp2_aTrue_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs500_msp2_aTrue_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs500_msp2_aFalse_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs500_msp2_aFalse_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs500_msp2_aFalse_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs500_msp10_aTrue_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs500_msp10_aTrue_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs500_msp10_aTrue_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs500_msp10_aFalse_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs500_msp10_aFalse_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs500_msp10_aFalse_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs500_msp50_aTrue_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs500_msp50_aTrue_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs500_msp50_aTrue_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs500_msp50_aFalse_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs500_msp50_aFalse_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs500_msp50_aFalse_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs500_msp100_aTrue_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs500_msp100_aTrue_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs500_msp100_aTrue_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs500_msp100_aFalse_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs500_msp100_aFalse_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs500_msp100_aFalse_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs500_msp200_aTrue_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs500_msp200_aTrue_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs500_msp200_aTrue_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs500_msp200_aFalse_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs500_msp200_aFalse_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs500_msp200_aFalse_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs500_msp500_aTrue_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs500_msp500_aTrue_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs500_msp500_aTrue_single0.8.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs500_msp500_aFalse_single0.2.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs500_msp500_aFalse_single0.5.sh &
srun --ntasks=1 --nodes=1 sh /Users/nguyennguyenduong/Dropbox/Document/2020/Nagoya_ctxafs/code/sh/mcs500_msp500_aFalse_single0.8.sh &
wait
